version: "3.8"

services:

  postgres-metabase:
    image: postgres:16
    container_name: postgres-metabase
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_metabase_data:/var/lib/postgresql/data
    networks:
      - metabase-network

  metabase:
    image: metabase/metabase:v0.63.15
    container_name: metabase-projetos
    restart: unless-stopped
    depends_on:
      - postgres-metabase
    ports:
      - "3037:3000"
    environment:
      JAVA_TIMEZONE: America/Sao_Paulo
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres-metabase
    networks:
      - metabase-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  postgres_metabase_data:

networks:
  metabase-network:
    driver: bridge