version: "3.8"

services:
  mysql-metabase:
    image: mysql:8.4
    container_name: mysql-metabase
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_metabase_data:/var/lib/mysql
    networks:
      - metabase-network

  metabase:
    image: metabase/metabase:v0.56.12
    container_name: metabase-github
    restart: unless-stopped
    depends_on:
      - mysql-metabase
    ports:
      - "3036:3000"
    environment:
      JAVA_TIMEZONE: America/Sao_Paulo
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: ${MYSQL_DATABASE}
      MB_DB_PORT: 3306
      MB_DB_USER: ${MYSQL_USER}
      MB_DB_PASS: ${MYSQL_PASSWORD}
      MB_DB_HOST: mysql-metabase
    networks:
      - metabase-network

volumes:
  mysql_metabase_data:

networks:
  metabase-network:
    driver: bridge